
title: "Konspirio"
email: merovex@gmail.com
venue: Virginia

description: >- # this means to ignore newlines until "baseurl:"
  A game of conspiracy and real-life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

future: false
sass:
  style: compressed
collections:
  faq:
    output: true
    permalink: /faq/:path/

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "page"
# Build settings
permalink: /posts/:title

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo

picture:
  source: "assets/images/fullsize"
  output: "assets/images/generated"
  suppress_warnings: true


kramdown:
  input                   : GFM
  hard_wrap               : false
  auto_ids                : true
  footnote_nr             : 1
  entity_output           : as_char
  toc_levels              : 2..4
  smart_quotes            : lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    disable               : true